---
- name: Playbook para hacer el deploy de la aplicaci贸n web WordPress
  hosts: frontend
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:
    - name: Eliminamos las descargas anteriores de wordpress.
      file:
        path: /tmp/wp-cli.phar
        state: absent 
  
    - name: Descargamos el c贸digo de WordPress con CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /tmp
        mode: "+x"

    - name: Hacemos MV para a /usr/bin para poder usarlo sin la ruta completa
      command: mv /tmp/wp-cli.phar /usr/local/bin/wp

    - name: Eliminamos instalaciones previas del directorio /var/www/html
      shell: rm -rf /var/www/html/*
    
    - name: Descargamos el codigo fuente de wpdonwload.
      command: wp core download --locale=es_ES --path=/var/www/html --allow-root

    - name: Configuraci贸n de WordPress CLI
      command: >
        wp config create
        --dbname={{ wordpress.WORDPRESS_DB_NAME }}
        --dbuser={{ wordpress.WORDPRESS_DB_USER }}
        --dbpass={{ wordpress.WORDPRESS_DB_PASSWORD }}
        --dbhost={{ wordpress.WORDPRESS_DB_HOST }}
        --path=/var/www/html
        --allow-root

    - name: Instalaci贸n de WordPress CLI
      command: >
        wp core install
        --url="{{ wordpress_configuracion.CERTIFICATE_DOMAIN }}"
        --title="{{ wordpress_configuracion.WORDPRESS_TITLE }}"
        --admin_user="{{ wordpress_configuracion.WORDPRESS_ADMIN_USER }}"
        --admin_password="{{ wordpress_configuracion.WORDPRESS_ADMIN_PASS }}"
        --admin_email="{{ wordpress_configuracion.WORDPRESS_ADMIN_EMAIL }}"
        --path=/var/www/html
        --allow-root