---
- name: Playbook para instalar la pila LAMP en el FrontEnd
  hosts: frontend
  become: yes

  tasks:
    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar el servidor web Apache
      apt:
        name: apache2
        state: present

    - name: Instalar PHP y los m贸dulos necesarios
      apt: 
        name:
          - php
          - php-mysql
          - libapache2-mod-php
        state: present

    - name: Habilitar el m贸dulo rewrite de Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Copiar el archivo de configuraci贸n de Apache
      template:
        src: templates/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 0644
      notify: Restart Apache

    - name: Copiamos el archivo de configuraci贸n de PHP
      copy:
        src: /home/ubuntu/Practica03-01IAW/WordPress/php/index.php
        dest: /var/www/html/index.php
        mode: 0755

    - name: Cambiar el propietario y grupo del directorio de Apache
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
